apiVersion: apps/v1
kind: Deployment
metadata:
  name: omke
spec:
  replicas: 1
  selector:
    matchLabels:
      app: omke
  template:
    metadata:
      labels:
        app: omke
    spec:
      containers:
      - image: okteto.dev/omke:latest
        name: omke
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "b9cff6c4-39af-4922-a098-4ab6b6d6ffef"
        - name: Vless_Path
          value: "/b9cff6c4-39af-4922-a098-4ab6b6d6ffef"
        - name: Vmess_UUID
          value: "d9b51f33-0d43-4434-b159-44e28f37a957"
        - name: Vmess_Path
          value: "/d9b51f33-0d43-4434-b159-44e28f37a957"
        - name: Share_Path
          value: "/v2link"
