apiVersion: v1
kind: Service
metadata:
  name: yoke
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP  
  ports:
  - name: "yoke"
    port: 8080
  selector:
    app: yoke
